version: "3.9"
services:
    nginx:
        image: imagestored/nginx:test
        ports:
            - "3000:8080" #Change to X:8080 to access on port X
        depends_on:
            - frontend

    frontend:
        image: imagestored/frontend:test
        depends_on:
            - backend

    backend:
        image: imagestored/backend:test
        restart: always
        environment:
            PGSTRING: postgres://postgres:example@db:5432/postgres # This string has to resolve to a Postgres database on version 11
        volumes:
            - ./media/:/code/media
        depends_on:
            - db

    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./data/:/var/lib/postgresql/data

    detectron2: # You can use either detectron2, which is slower but more accurate, or yolo, which is faster but has less accurate results, and is very leigthweight.
        image: imagestored/detectron2:test
        environment:
            BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
            FETCH_INTERVAL: 10 # This is the interval the labeler will poll for new images in seconds
        depends_on:
            - backend
        profiles:
            - detectron

    yolo: # You can use either detectron2, which is slower but more accurate, or yolo, which is faster but has less accurate results, and is very leigthweight. 
        image: imagestored/yolo:test
        environment:
            BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
            FETCH_INTERVAL: 10 # This is the interval the labeler will poll for new images in secondsend
        depends_on:
            - backend
        profiles:
            - yolo

    search: # CLIP-based search engine to replace the default search feature
        image: imagestored/search:test
        restart: always
        environment:
            BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
            PORT: 5000 # Pick a port to run the search-backend on
        volumes:
            - ./imageFeatures/:/code/features
        depends_on:
            - backendd
        profiles:
            - search

    face: # Facial recognition
        image: imagestored/face:test
        restart: always
        environment:
            BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
            PORT: 5000 # Pick a port to run the search-backend on
        volumes:
            - ./faceFeatures/:/code/features
        depends_on:
            - backendend
        profiles:
            - face

    autoimport: # Automatic import of media in the "import" directory
        image: imagestored/autoimport:test
        restart: always
        environment:
            BACKEND_URL: backend:4000 # Set this to the address the backend will be accessible on
            SLEEP_TIME: 100 # How long to wait after each upload (ms)
            POLLING_RATE: 10000 # How often to check for new files (ms)
        depends_on:
            - backend
        volumes:
            - ./import/:/code/importrt/:/code/import
        profiles:
            - import
