name: build&push

on:  
  push:
      branches: [ main ]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagestored/frontend:latest
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_detectron2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagestored/detectron2:latest
          file: ./detectron2/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_yolo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagestored/yolo:latest
          file: ./yolo/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: imagestored/backend:latest
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
